### ISSUE TITLE
[UI] Server filter keeps showing "LAN"

### ISSUE THREAD

**Issue by Kako38** [supraball/issues#10]
When you enter the server browser, the filter shows "LAN" although the browser shows the Internet servers.

Changing the filter from Internet to LAN then to Internet again does show "Internet" in the filters. However, clicking on the button to edit the filter and then cancelling will make "LAN" reappear instead of "Internet", although you didn't change anything.

**Comment by Marenz** [comment]
The drop down menu doesn't really do anything. It's a left over. Will be removed soon.

**Comment by Timoses** [comment]
Fixed. It'll only show Internet now : P

**Comment by DavidM1337** [comment]
why not remove it, if we don't use it anyway?

**Comment by Timoses** [comment]
Disabled it for now until redesign ; )
