### ISSUE TITLE
Launcher doesn't start

### ISSUE THREAD

**Issue by Akatos** [supraball/issues#100]
Since today (just got back from vacation) the supraball launcher (steam beta) isn't working for me after having installed the update(s). Everything I get is the splashscreen, the launcher itself doesn't open at all. I took a look into the log and the line that appears to be the problem is "QObject::connect: No such slot Application::emitConnecting()". Here's the full log:
http://pastebin.com/4QfRDGyY

Reinstalling the game and restarting steam didn't help. Is this a known issue or am I the first to report this problem? Thanks in advance!

**Comment by GTrebaol** [comment]
having troubles with the masterserver at the moment, check https://www.reddit.com/r/Supraball/comments/3gz14h/masterserver_broken_atm_game_wont_start/ for updates I guess :)

**Comment by Akatos** [comment]
Yeah I already saw that, guess we'll have to wait then. Thanks for the answer!

**Comment by Timoses** [comment]
Should be fixed. Thanks for reporting.
