### ISSUE TITLE
No connection to masterserver on launch; firewall ports?

### ISSUE THREAD

**Issue by mvarendorff** [supraball/issues#101]
After finding the game on 9gag I was eager to try it out. However I constantly get the two lines
```
Connecting to masterserver ...
Failed to connect! Retrying ...
```
After searching around in the issues I found that port 8990 needs to be open in the firewall. Are there any more requirements (except for the Steam-Ports) I am not aware of? I could not find anything in the FAQ but I think if there is that might be worth an entry :)

Cheers
geisterfurz007

**Comment by boyhitsworld** [comment]
Thanks for raising the issue. Clients need to be able to connect to ports 8991 and 8992 on our masterserver, and then to whatever ports the game servers have been configured to use (by default these are 7777 and 27015).

I'll add a mention about those ports to the faq, but be warned, if you're behind a firewall that has a whitelist for outbound connections, you're in for bad time. Game servers could be running on almost any port, and we have zero control over what server admins choose to use.

**Comment by mvarendorff** [comment]
Welp guess I am then. The network administrators have to open them one by one so I guess playing this game is going to be hard for me then.
Thanks for your fast response and good luck with the game!
