### ISSUE TITLE
Auto-spectate enables after each goal

### ISSUE THREAD

**Issue by viocar** [supraball/issues#12]
When spectating a game, the Auto Spectate [C] function reactivates even if it were previously turned off.

Reproduction:
1. Spectate a game
2. Disable Auto Spectate [C]
3. When a goal is scored, Auto Spectate will activate itself once again - sometimes twice.

**Comment by Kako38** [comment]
Seems like it also reactivates itself after idling for some seconds in Free Camera, I suppose it is a related bug. (Spectate -> Free Camera [0] -> Don't touch anything)

**Comment by DavidM1337** [comment]
The button C was never supposed to disable the auto system. It can just reactivate it.

We changed the camerasystem, maybe look if you are happy with it now and tell us here.
