### ISSUE TITLE
Impossible to run the game error 0xc000007b

### ISSUE THREAD

**Issue by gbrgs** [supraball/issues#14]
I try to install the game twice, but no difference, I still have the same error message at launch. 

"UDK.exe - The application did not start (0xc000007b)"

I'm on Win 8.1 (Processor AMD & Graphic Card ATI), that's the problem ?

**Comment by Timoses** [comment]
Are you running a 64bit system? 
Try running the [...]\Supraball\Binaries\Win32\UDK.exe .
Feel free to report back your results.

Edit:
If you are unsuccessful have a look at this: http://steamcommunity.com/app/219640/discussions/0/630802979209945672/

**Comment by gbrgs** [comment]
Yes, i'm running a 64bit system, 
Great, it work now ! 
Thanks a lot for your anwser !

**Comment by Timoses** [comment]
What did you use to fix it?

**Comment by gbrgs** [comment]
I'm running the game with the path  [...]\Supraball\Binaries\Win32\UDK.exe, like you said. 
I think my 6 core processor not support the game in 64 bit, but it works now ;) 
Thanks again!

**Comment by Timoses** [comment]
Glad to hear : ). Thanks for the info.

Have fun :D
