### ISSUE TITLE
Players can be knocked out of bounds

### ISSUE THREAD

**Issue by ghost** [supraball/issues#17]
It's either over it or threw it. There was a lot of action which caused a player to end up outside the court.

We tried bumping him back in play, but we were not able to do so.

Video: https://www.dropbox.com/s/0r65pug1cxco46q/OutofBounds.mp4

**Comment by Timoses** [comment]
Possibly related to #7 ?

**Comment by zarakon** [comment]
I saw this happen yesterday.  Someone was in my goal box, I hit him, and he ended up behind the glass.  I'm not sure if someone else hit him at the same time or not.  I believe he was right by the goalpost at the time, and I hit him in that direction.  Maybe he went through the goalpost?

**Comment by Fooman1** [comment]
I saw 3-4 players go to a corner on DB-pitchwalls and boost each other straight up into the air.  Eventually one got boosted high enough to walk on an invisible plane, then fell down out of bounds.

**Comment by Seikah** [comment]
Saw the patch notes suggest this may be fixed; it is not, or at least not entirely. This afternoon, I was knocked out and hit onto the goal crossbar, then respawned // woke up behind the glass. Sadly, I only have footage of walking out of bounds, not the establishment of the bug itself.

**Comment by DavidM1337** [comment]
Aaah, that section of the wall right above the goal is still thin, didn't make it thicker, like the rest!
So it makes sense, that it happened only there.

**Comment by Seikah** [comment]
Seems to occur still: knocked someone out on top of the goal, got behind the wall.

**Comment by Marenz** [comment]
Assuming fixed, reopen if not.
