### ISSUE TITLE
[UI] Can't change spectator controls

### ISSUE THREAD

**Issue by Kako38** [supraball/issues#22]
I can't seem to be able to edit the spectator controls, I can only select the "Change camera view" entry.

**Comment by Timoses** [comment]
Does this mean that you can't set a new bind in Options? (Meaning you actually can't set one or you can set them in Options but they don't work ingame?)

**Comment by Kako38** [comment]
In the options.

**Comment by Marenz** [comment]
I assume this is fixed, reopen if not.
