### ISSUE TITLE
Game Freezes

### ISSUE THREAD

**Issue by TesoX** [supraball/issues#23]
Hey,

my friend have an probelm every 20 seconds stand the game for 2-10 seconds still.
He tell me its like the game frozes.

Edit: The complete PC freezes.

I hope someone can help us.
TesoX

**Comment by DavidM1337** [comment]
Could he please try to run the 32 bit version instead of the 64 one,  if he does.
Run supraball/binaries/32bit/udk.exe

Does it still happen then?

**Comment by TesoX** [comment]
I ask him when he is back at home. If it works I'll tell you.

**Comment by TesoX** [comment]
The 32Bit .exe works fine thank you !
