### ISSUE TITLE
Penalty mark/spot is missing in low details

### ISSUE THREAD

**Issue by declis** [supraball/issues#25]
![screenshot00001](https://cloud.githubusercontent.com/assets/6698539/2937366/6e5d2bc2-d89c-11e3-836b-cbd63522cc12.jpg)
![screenshot00000](https://cloud.githubusercontent.com/assets/6698539/2937367/6e62e9d6-d89c-11e3-9a67-d65a0eab7e52.jpg)

The spot is always a good orientation if you're keeper (middle of the goal etc)

**Comment by Marenz** [comment]
I think this is fixde now, reopen if not
