### ISSUE TITLE
Enhancement: Let us hear when a player is charging their shot while spectating.

### ISSUE THREAD

**Issue by ev88** [supraball/issues#28]
Currently you can't hear if a player is charging their shot while spectating.  I think this would be a useful feature to have.

**Comment by DavidM1337** [comment]
Yup, it wouldn't be a feature though, its just currently a bug that the spectators dont hear it

**Comment by mielipuolinen** [comment]
I'm not having this problem on 0.2.4 ?
Only if the camera is too far from the player.

**Comment by Marenz** [comment]
I think this is fixed... reopen if not.
