### ISSUE TITLE
[BUG] Ball randomly disappears between shots.

### ISSUE THREAD

**Issue by ev88** [supraball/issues#29]
After a player passes the ball it will completely disappear for me.  I can hear it just fine.  Only after a player picks the ball back up can I see it.  Unfortunately I'm not sure what causes this.  It's a fairly rare bug; I've only experienced it twice so far, but it's certainly an issue obviously.

**Comment by DavidM1337** [comment]
We know the reason for this, thanks for submitting it

**Comment by Kattleya** [comment]
When will this be fixed? Happens more often to me now, sometimes doesn't happen at all

**Comment by Marenz** [comment]
Should be fixed.
