### ISSUE TITLE
'kickoff' timer bug when player DCs/leaves

### ISSUE THREAD

**Issue by randymagnum** [supraball/issues#30]
So after a goal, the game informs each player to get to their side of the pitch/court/field. The ball won't spawn until all players have satisfied this condition, or until the ball-spawn timer has expired (30-60 seconds?).

What I've noticed is the spawn timer for the ball runs for the full duration if a player left the game on the opposition's side of the field near the time of a goal. The game treats that player as if they are still in the game, and still on the wrong side of the mid-field line - making all the players wait for no real reason.

**Comment by Timoses** [comment]
Thanks, randymagnum, for reporting. We know this issue exists and will get to it in the future. So far we've not come to this one, yet, as there are some other more urgent issues :) .
