### ISSUE TITLE
KO not always in sync with server

### ISSUE THREAD

**Issue by isigold** [supraball/issues#32]
From what I observered last game, the client does not always recognize being ko'd.
As client it is observable by the missing "unconscious"-Text displayed and no screen tilt.
This happened a few times at the border of the penalty box, i.e. keeper pulled me into penbox and killed me.
My assumption: As I was close to the border of the penalty box it might be that my client still thought to be outside of the penalty box and thus only recognized being hit but not ko'd.

**Comment by Marenz** [comment]
I think this is fixed
