### ISSUE TITLE
Wrong program name in Add / Remove Program.

### ISSUE THREAD

**Issue by 0xShammah** [supraball/issues#36]
Spotted this entry in my Add / Remove Programs window.
The selected item is indeed Supraball.

![image](https://cloud.githubusercontent.com/assets/1854439/2942423/25980bfa-d9b4-11e3-8df8-1d6cb53132c9.png)

**Comment by Timoses** [comment]
It is very sad to see you uninstalling Supraball. To prevent this we hid the game.

Just kidding... Thanks for reporting this : )

**Comment by Marenz** [comment]
This is an issue with UDK though, not sure we can do anything about this.
