### ISSUE TITLE
I can't see servers and the game crash when I try Training mode

### ISSUE THREAD

**Issue by babineking** [supraball/issues#38]
I don't know what to do, the game was working yesterday, I install the game a second time to try and no progress...

This is the log thing, the part with "critical" stuff

 [0016.80] Log:    World db-frontendmap.TheWorld [target]
   GFxDBFrontEnd_JoinGame db-frontendmap.TheWorld:PersistentLevel.Main_Sequence.GFxDBFrontEnd_0.GFxDBFrontEnd_JoinGame_0  (ObjectProperty DBGame.GFxDBFrontEnd_Screen:DBGameInfo)
   DBMasterServer Transient.DBMasterServer_1  (DelegateProperty DBGame.DBMasterServer:listDelegate)
   HttpRequestWindows Transient.HttpRequestWindows_1 (root) (DelegateProperty Engine.HttpRequestInterface:__OnProcessRequestComplete__Delegate)

[0016.80] Critical: appError called: World db-frontendmap.TheWorld not cleaned up by garbage collection!
   World db-frontendmap.TheWorld [target]
   GFxDBFrontEnd_JoinGame db-frontendmap.TheWorld:PersistentLevel.Main_Sequence.GFxDBFrontEnd_0.GFxDBFrontEnd_JoinGame_0  (ObjectProperty DBGame.GFxDBFrontEnd_Screen:DBGameInfo)
   DBMasterServer Transient.DBMasterServer_1  (DelegateProperty DBGame.DBMasterServer:listDelegate)
   HttpRequestWindows Transient.HttpRequestWindows_1 (root) (DelegateProperty Engine.HttpRequestInterface:__OnProcessRequestComplete__Delegate)

[0016.80] Critical: Windows GetLastError: The operation completed successfully. (0)
[0019.25] Log: === Critical error: ===
World db-frontendmap.TheWorld not cleaned up by garbage collection!
   World db-frontendmap.TheWorld [target]
   GFxDBFrontEnd_JoinGame db-frontendmap.TheWorld:PersistentLevel.Main_Sequence.GFxDBFrontEnd_0.GFxDBFrontEnd_JoinGame_0  (ObjectProperty DBGame.GFxDBFrontEnd_Screen:DBGameInfo)
   DBMasterServer Transient.DBMasterServer_1  (DelegateProperty DBGame.DBMasterServer:listDelegate)
   HttpRequestWindows Transient.HttpRequestWindows_1 (root) (DelegateProperty Engine.HttpRequestInterface:__OnProcessRequestComplete__Delegate)

**Comment by Timoses** [comment]
And it has worked before reinstallation?
If so, what exactly did you do to reinstall? (install old 0.2.3 and update? install new 0.2.4?)

**Comment by Marenz** [comment]
This looks quite familiar actually. Can you show us the complete log please?

**Comment by babineking** [comment]
I installed only 0.2.4, but I just installed it a fourth time, and now the 32 bits one works!
The server finding problem is that I need to wait a bit and refresh it and go through the options then I get back on the list and I can see the list of servers.
I don't have the log anymore I think.

**Comment by Marenz** [comment]
Hmm judging from the log above I wouldn't expect a change to 32 to fix this. If it happens again, make sure to give us the complete log

**Comment by babineking** [comment]
I will! thx for all your answers !
