### ISSUE TITLE
Home Server Connection Issues

### ISSUE THREAD

**Issue by Magikarp1** [supraball/issues#39]
Now setting up a server in this game seems to be a bit of a pain. When my server is set up (using instructions on the website), the server is visible on the master server list but I nor anyone else can connect to it. When we attempt to, we are constantly clicking the join game button and ultimately the game crashes. I, as server host, have had some luck in connecting via console command "open 127.0.0.1".
I also attempted to remove all passwords from the server when starting it up via a command line argument 
What can I do to stop this from occurring and finally achieve a good game?

**Comment by Timoses** [comment]
It's Alpha. : ).
But still, we're trying to solve that and many other things. So any help from the community is greatly appreciated!

> have had some luck in connecting via console command "open 127.0.0.1".
> Does this mean it works everytime when trying `open 127.0.0.1`?

P.S.: It's usual that you can't connect to your own server from server browser. You would try to connect to your own external ip ; ).

**Comment by Magikarp1** [comment]
Almost every time.  I understand that an alpha game is not gonna be as good as skyrim in weeks, but how can one enjoy the game with friends if one cannot connect to his server? Apart from that  though, it is a amazing game.

**Comment by Timoses** [comment]
Did you/or your friend (whoever is hosting the server) open the game port? 7777 (UDP) by default.

**Comment by Magikarp1** [comment]
Yep, Done to the instructions on the website.

**Comment by Timoses** [comment]
In the next version we implement error messages when connecting to servers. So maybe you'll get a clue then. Until then I wouldn't know how to help you, right now.

**Comment by Magikarp1** [comment]
![8f203bf4bb5cbbdbe463952bec3a3e3d](https://cloud.githubusercontent.com/assets/7572743/3031138/ef507b72-e048-11e3-9c8a-39eabcf7338c.png)
Maybe this could help.

**Comment by Marenz** [comment]
This is still version 0.2.4. Have you tried the new update?

**Comment by Marenz** [comment]
Oh, sorry disregard that

**Comment by Timoses** [comment]
Well, you're obviously updating the master server properly. So your server should be visible at http://supraverse.net/supraball-serverlist/index.html and in the game browser.

Are you (or players that want to join your server) still crashing when trying to join your server in version 0.2.5?
Is everybody crashing?
What happens when a player from outside tries to join your server by console command:
`open <yourIP>`?

**Comment by JOJOsaysbreee** [comment]
I too am having these same issues except I CAN connect to my server either via the list or the in game command, but none of my friends can. I have forwarded the ports necessary, I have created the batch file with all the server properties in it just as the website explains. Nothing. Every time they try they get a "3-2-1. Timeout."

**Comment by JOJOsaysbreee** [comment]
We are also using 0.2.5 so updates is not an issue

**Comment by Timoses** [comment]
Firewall blocking?

> I too am having these same issues except I CAN connect to my server [...]

Is this a local server for you? Then you shouldn't be able to connect via ingame browser since the IP is the external one. Except when you are using ?serverIP=<yourLocalIP>, which I hope you did not. To check your external IP visit [here](http://www.whatismyip.com/) for example.

**Comment by Marenz** [comment]
@JOJOsaysbreee  the log you posted on FB was from your client, but we need the server log

**Comment by Magikarp1** [comment]
I just sorted it out, my fix was to change the ports from 7777 to another one

**Comment by Marenz** [comment]
Hu. That means something was already listening on that port or it was somehow blocked. Weird. Glad you solved it.

**Comment by Marenz** [comment]
@JOJOsaysbreee  maybe you can try the same.

**Comment by JOJOsaysbreee** [comment]
No I tried both ports. It's not an issue with ports because I use IP passthrough. If anyone knows what that means, it basically just means my IP is completely open to all ports. They're automatically all open and forwarded. I don't need to port forward. It's another issue. I'm just going to blame it on alpha. I've tried everything. I've been working at it for hours and hours everyday for 2 weeks. It's not working and just because I'm female everyone just tells me how to forward ports like I'm an idiot.

**Comment by JOJOsaysbreee** [comment]
Where can I find the server log? In the documents

**Comment by JOJOsaysbreee** [comment]
![server log](https://cloud.githubusercontent.com/assets/7661967/3072928/1cf0fab2-e2d2-11e3-8043-668ba60b5c5e.png)

This is what my server does when I open it.

**Comment by Timoses** [comment]
Should be in your [...]\Supraball\UDKGame\Config folder. (all logs are put in there, whether you play or make a server).

**Comment by JOJOsaysbreee** [comment]
Also, it says latest version is 0.2.4, but I'm using 0.2.5

?

**Comment by Marenz** [comment]
Yeah, that is just an old setting on the master server, you can ignore that.
Is the ip in that log your current ip? the 23.122.15.75?

**Comment by JOJOsaysbreee** [comment]
Yes

**Comment by JOJOsaysbreee** [comment]
I use that IP for my Minecraft server also

**Comment by JOJOsaysbreee** [comment]
When someone tries to connect and gets timed out, it starts going "Failed to spawn bot." over and over.

**Comment by Marenz** [comment]
I can't ping that IP. And a Port scan also says it seems to be down. I also tried connecting to the supposedly open udp port 7777. What port is minecraft on running? I could check the ip maybe using the minecraft port

**Comment by JOJOsaysbreee** [comment]
Oh well I had closed it Try again.

**Comment by Marenz** [comment]
The Failed to spawn Bot is when a player was on your server and left again, there is some old udk code that tries to replace that player with a bot. It's not a problem, just a bit spammy in the logs

**Comment by JOJOsaysbreee** [comment]
I'll keep it open this time, try again. Minecraft uses 25565 port, but I've had it down for maintenance all week. They just did updates.

**Comment by JOJOsaysbreee** [comment]
If it's a setting in my router, other than ports, I can probably fix it.

**Comment by Marenz** [comment]
I think it's easier to do this over chat. Could you join our IRC? http://webchat.quakenet.org/ channel #supraball.preview

**Comment by JOJOsaysbreee** [comment]
Well I have a sleeping baby in my lap right now :/

**Comment by Marenz** [comment]
No no, not audio, it's just text chat

**Comment by JOJOsaysbreee** [comment]
Well that's what I mean, I have one hand lol. I can try.

**Comment by Marenz** [comment]
Issue resolved in IRC. Something with the setup, but doesn't seem to be an error with the game

**Comment by JOJOsaysbreee** [comment]
Not the games fault! Router miscommunication! Thanks!
