### ISSUE TITLE
Random Charge

### ISSUE THREAD

**Issue by 0xShammah** [supraball/issues#4]
Sometimes when I have the ball, my character starts charging a shot, even though I am pressing no buttons at all. If I then click on my left mouse button, the charge stops, but the ball will be shot away ofcourse.

**Comment by Swarlston** [comment]
Hi, there is some bug i know of which sounds kinda like that.
The bug I mean occurs when you kick the ball and catch it afterwards.
Is that the bug you mean?

**Comment by 0xShammah** [comment]
I'm not entirely sure, but I did notice it happening right after I would
catch the ball, so this could be likely the case.
Op 6 mei 2014 02:04 schreef "Swarlston" notifications@github.com:

**Comment by AlonTavor** [comment]
I can confirm it happens when you kick before catching the ball, some kind of client/server missync? Maybe make "shoot" a different command? Not sure how the netcode works on UT3

**Comment by Timoses** [comment]
I suppose this was fixed.

**Comment by AlonTavor** [comment]
confirmed, couldn't reproduce with pktlag=500 and pktloss=30.
