### ISSUE TITLE
"Get rid of the ball" timer kept running while ball was in play

### ISSUE THREAD

**Issue by zarakon** [supraball/issues#41]
I was playing as keeper on red team.

I caught a ball that was rolling toward me.  I may have grabbed it right on the front edge of the box, but I'm not exactly sure.  I know I was moving forward as I grabbed it.

I passed it downfield immediately, but the "get rid of the ball" timer kept running.  I tried stepping out of the goal area in case it thought I still had the ball, but that did not affect it.    Also, my team was passing the ball around, so they obviously didn't see it still in our goal area.

After the 10 seconds, the ball disappeared and went to the other team for a goal kick.

**Comment by Marenz** [comment]
Thanks for reporting. Bug is known and already fixed in the next release :)
