### ISSUE TITLE
Charge bar stuck

### ISSUE THREAD

**Issue by 0xShammah** [supraball/issues#42]
While in the middle of charging a shot, the game ended and the server reloaded the map. Upon rejoining, my charge bar was there as if I was still charging, even though I did not hold the bar. It was just there being rendered at the state of the previous game. I asked for the ball, and when I recharged and released the ball, the bar finally disappeared.

**Comment by Marenz** [comment]
Thanks for reporting. Already reported though: https://github.com/supraball/issues/issues/31

**Comment by 0xShammah** [comment]
Darnit, I even searched for it! ;<

**Comment by GTrebaol** [comment]
If you slack in your keeper box and the countdown reach 0 while you were charging the bug occurs too

**Comment by Timoses** [comment]
Reopened because of

> If you slack in your keeper box and the countdown reach 0 while you were charging the bug occurs too

**Comment by Timoses** [comment]
fix https://github.com/supraball/supraball/pull/328
closed
