### ISSUE TITLE
0.2.5 Server browser displayed pings are too high

### ISSUE THREAD

**Issue by Fooman1** [supraball/issues#43]
I ping about 90 when I am in the NY servers, but the browser displays around 200.

200 to Helsinki, it displays around 410.

**Comment by DavidM1337** [comment]
sounds safe to me, that we just take half of the ping to be close enough

**Comment by mielipuolinen** [comment]
I'm having it a bit more interesting.
FYI: All EU-Helsinki servers are located in same host. So you would expect nearly the same ping.

My ping to the host is about 10-15ms, in game its about 20ms, for all Helsinki servers.

On the server browser it shows huge differences between servers no 7 and no 8. First might be 50ms-80ms and the second 80ms-100ms.

no 7 using 27088TCP
no 8 using 27089TCP
If that matters for pinging.
