### ISSUE TITLE
Issues with keyboard!

### ISSUE THREAD

**Issue by charizardlaranja** [supraball/issues#44]
I cant walk or do anything which has hotkeys set on my keyboard, although when i press "R", i can type normally. Strangely, when I switch my walking/shooting hotkeys, they work. All letters work while typing, so I know its not related to my keyboard not working.

**Comment by Timoses** [comment]
Sad to see this pop up again : (.
Check this issue: https://github.com/supraball/issues/issues/3
Unfortunately, we did not find out what caused this problem.

**Comment by mielipuolinen** [comment]
You would not have a PS/2 keyboard to try out?
Sounds to me a driver issue. If you're using USB keyboard in USB3.0 port, try changing it to USB2.0 port.

If you got some other input devices, try removing them and possibly remove drivers for them too.

In case you have programs running which can show on top of the game (Xfire, mumble, steam, etc.), try closing these too (and restart the game, make sure it's run as administrator). In case these would capture controls.

**Comment by Marenz** [comment]
I am assuming this is some problem with the computer and not the game. Closing this now as I don't see any further activity here. Feel free to re-open.
