### ISSUE TITLE
score two goals at once

### ISSUE THREAD

**Issue by cajuncook** [supraball/issues#45]
Was playing in a pub today, and our team scored two goals at once at the start of the match. Other team had no keeper, so one of our players walked the ball in, and shot it as he crossed the line. Score became 2-0 when it (of course) should have been 1-0.

**Comment by DavidM1337** [comment]
I'd say it was a touchdown after the shot, because the ball still lives in the goal for a very short time.

**Comment by Marenz** [comment]
I think we fixed this, reopen if not.
