### ISSUE TITLE
Graphic Issues

### ISSUE THREAD

**Issue by vouly** [supraball/issues#46]
I have some serious graphic issues with this game. Everything is displayed twice. One time red and one time blue. I see the ball twice, too. (See pictures).

![supraball_game](https://cloud.githubusercontent.com/assets/7618497/3007112/a6e34f00-de6c-11e3-8942-8ca60f79ef07.png)
![supraball_menu](https://cloud.githubusercontent.com/assets/7618497/3007113/a6e48a64-de6c-11e3-8977-bbf7f97eee32.png)

I tried to run the game in a lot of different compatibility modes, but nothing helped. I already tried to reinstall the game (installed everything).

My PC specs are:
OS: Windows 8.1 64bit
CPU: Intel Cor I7-4770 @ 3,4GHz
Ram: 16Gb
Graphics: NVIDIA GeForce GTX 770

So I believe this shouldn't be a problem. Hope you find a solution for that. 
Thanks!

**Comment by Timoses** [comment]
Forgot your 3D glasses ó.Ò..

Have you tried running the 32-bit version? ([...]\Supraball\Binaries\Win32\UDK.exe). Please report back in case this solves the issue.

**Comment by DavidM1337** [comment]
This is Nvidia 3dVision
Disable it in your Nvidia settings.
Or hit Ctrl+T

**Comment by vouly** [comment]
@Timoses 
I had the same problem with the 32-bit version, but it was just an configuration problem on my site, sorry. 

@DavidM1337 
It seems like it was totally my fault then... :( Never had any problems with the Nvidia settings until this point. Tried to disable those settings and now it works perfectly! (Tried Ctrl+T and it works, too.)

Thanks for your help!
