### ISSUE TITLE
Game crashes when I open server browser

### ISSUE THREAD

**Issue by isurakka** [supraball/issues#47]
This happens on fresh install.

You can find logs and dumps here:
http://37.139.17.207/public/supraball/logs/

Files with "debug" in their name have had the suppress stuff commented in UDKEngine.ini.

**Comment by Timoses** [comment]
Thanks for the log Frugle. We're on it ; ).

**Comment by isurakka** [comment]
Looks like there are multiple people with the same problem. http://www.reddit.com/r/Supraball/comments/25usrc/built_with_udk_has_stopped_working/

**Comment by Marenz** [comment]
Problem was when in certain constellations the json string would contain unmatched `[`. This would bring the native JSON parser from UDK down. Work around it now by stripping unmatched `[]`s
