### ISSUE TITLE
Speedhack

### ISSUE THREAD

**Issue by flownerous** [supraball/issues#48]
A player was repeatedly joining and travelling at super speed. Across the map in 1 second.

**Comment by Marenz** [comment]
There is a setting in UDKGame.ini called MaxTimeMargin to detect & prevent speed hacks. I haven't found the best value for it, but try values from `0.2` to `2`. If the value is not well set it could cause high ping players to be detected as speedhackers (we the consequence of them being slowed down)

**Comment by flownerous** [comment]
Thanks! I'll try that out.
