### ISSUE TITLE
Using console during training prevents you from joining servers.

### ISSUE THREAD

**Issue by ev88** [supraball/issues#5]
If you use the console during training to change your FOV for example, it won't let you connect to a server afterwards.  I ran into this same issue with Hawken so it wouldn't surprise me if this were a default UDK/Unreal feature to prevent hacks/cheating.

**Comment by mAkulA** [comment]
Do you know how to fix this? I opened the console during training and now I can't join any game even after reinstalling Supraball.

**Comment by Timoses** [comment]
@mAkulA : not even by typing the IP in the console? ("open <ip>")

[Server List](http://andrasklikk.com/supralist/)

**Comment by mAkulA** [comment]
@Timoses I didn't try that. How can I know the IP of a server?

**Comment by Timoses** [comment]
By clicking on [Server List](http://andrasklikk.com/supralist/) 
; )

**Comment by Marenz** [comment]
Assuming fixed/work-around, reopen if not
