### ISSUE TITLE
NSIS Error ;_;

### ISSUE THREAD

**Issue by Shawndi** [supraball/issues#51]
![whysupraball](https://cloud.githubusercontent.com/assets/7623338/3008796/ee4af776-ded0-11e3-94f9-22aae2265def.png)
Idk what to do any advice?

**Comment by Timoses** [comment]
Perhaps your download got corrupted. There was a big wave coming in and the download server had problems handling all the requests : P. Try redownloading.

**Comment by Marenz** [comment]
Usually corrupted download, yes.
