### ISSUE TITLE
.2.5 wont load launcher once downloaded

### ISSUE THREAD

**Issue by noobsnip3r** [supraball/issues#52]
I have now downloaded the prounreal.org and eoreality.net files and all of the times I click it the windows smartscreen opens. I run it anyways and then the administrator permission screen pops up. I click allow and then like it should launch nothing happens just my desktop no errors or anything. i check the downloads on my browser (chrome) and says it is removed. so what the heck?

**Comment by Timoses** [comment]
Thank you for reporting. Another one has this issue as well ( [reddit](http://www.reddit.com/r/Supraball/comments/25yz62/wont_open_up_after_installation/) ).
We'll get back to you.

**Comment by Marenz** [comment]
Assuming fixed, reopen if not
