### ISSUE TITLE
Not valid win32 app / failed to initialize properly .. Game doesn't start.

### ISSUE THREAD

**Issue by Hadzy-1** [supraball/issues#53]
Hello,

I knew about SupraBall from a friend and it seemed nice so I went to download it.
After downloading v0.2.5 I opened it and it was installing, it also updated the DirectX ...
After it finished I opened the shortcut on my desktop and this appears: (Also appears when I open the launcher)

![](http://i.imgur.com/olyeWv1.png)

So I went to the forums and searched, found that some says open it from the binaries folder/Win32/UDK.exe so i tried, and I got the following message:

![](http://i.imgur.com/SB5s3Iy.png)

So I re-installed it, same happens .. Any ideas on how to make the game work?

Cheers,
Hady Hayman (IamHadzy)

**Comment by Timoses** [comment]
Try reinstalling DirectX (http://www.microsoft.com/en-us/download/details.aspx?id=35).
Also, it would be great if we could see your log file (located in [...]\Supraball\UDKGame\Logs).

**Comment by Hadzy-1** [comment]
Hey Timoses,
Thanks for replying... I've tried to install directX but it told me this:

![](http://i.imgur.com/F3Gsq0d.png)

I've also searched for the logs folder, but it doesn't exist.
Any other advice?

**Comment by Timoses** [comment]
The only reference to this error related to UDK.exe I could find up to now is [this](http://forums.tornbanner.com/showthread.php/5828-UDK-exe-has-stopped-working).

Do you have other programs running aside? Try exiting all unnecessary ones. 
It's a long shot, but try moving `D3DCOMPILER_43.dll` file from your Windows\system32 folder (back it up somewhere?) and reinstall the game.

If that doesn't work, try [uninstalling DirectX](https://www.raymond.cc/blog/how-to-uninstall-directx-and-reinstall-to-repair-directx/) and reinstall it.

**Comment by DKarev** [comment]
![image](https://cloud.githubusercontent.com/assets/7656729/3038992/8decc678-e0d5-11e3-908c-d7d26e009c82.png)

I have the same problem. I tried most of the things up there. This is screenshot from my log files

**Comment by Marenz** [comment]
Somehow it sounds like your windows 32bit emulation isn't working properly. Try starting the UDK in the Binaries/Win64 folder directly.

**Comment by Marenz** [comment]
Are you using Windows XP?

**Comment by Hadzy-1** [comment]
Hey Marenz,
I've tried to open it from the win64 folder but it told me that it's not valid (Or something similar).
Yes, I'm using Windows XP .. anyway I had to install a new windows for other issues so I'll have windows 7 when my PC get fixed and I'll try it tomorrow.

**Comment by Marenz** [comment]
Hmm my guess is it will just work then. Too bad, I had one further idea to fix this.

**Comment by DKarev** [comment]
I tried UDK and the same error was showed. Yes, I am using windows XP. So is there a way to fix it without installing a new Windows?

**Comment by Timoses** [comment]
@Marenz your chance : )

> Too bad, I had one further idea to fix this

**Comment by Marenz** [comment]
@DKarev so you tried both the launcher, the Binaries/Win32/UDK.exe and the Binaries/Win64/UDK.exe ? They didn't all give you the same error right?

In any case, one possible fix: Install .Net Framework: http://www.microsoft.com/en-US/download/details.aspx?id=17718

Tell me if that fixes it. Please also test whether
- Your errors happen when you use the launcher
- Your errors happen when you launch the 64bit UDK
- Your errors happen when you launch the 32bit UDK

**Comment by Marenz** [comment]
Regarding the launcher win32 error, I got that fixed now. Problem on our side.

**Comment by Hadzy-1** [comment]
Marenz, Thanks .. One million thanks...
I've installed .NET and it works now .. The only downside is it's laggy.. (Faster with LOW visuals but still laggy) However, I gotta start playing now.

I opened it from the Win32 folder using UDK.exe (Launcher and UDK in Win64 don't work)

**Comment by Hadzy-1** [comment]
I'm getting 8-10 FPS in training.
And 5-7 FPS in multiplayer ... It's really not like a game xD
I want any solution to at least double the FPS I already get.

My specs :
Intel {R} Pentium {R} 4 CPU 3.00GHz 3.00GHz, 2.96 GB of RAM

**Comment by Marenz** [comment]
See if the latest update changed things for you.

**Comment by Hadzy-1** [comment]
Marenz, The launcher now works.
However, I suggest to either:
- Make the game run better on slow PCs.
  Or Add some really low visuals with no effects, etc.

I know your work is hard, but I'm not able to play it with such a low FPS....

**Comment by Timoses** [comment]
We'll try to get some more graphic options work done soon. Hang on tight ; ).
