### ISSUE TITLE
When ever i try to open SupraBall it keeps crashing someone help me!

### ISSUE THREAD

**Issue by mame123** [supraball/issues#55]
When ever i try to open SupraBall it keeps crashing someone help me!What do i do?

**Comment by Timoses** [comment]
Are you getting any errors?
Try running 
[...]\Supraball\Binaries\Win32\UDK.exe
or
[...]\Supraball\Binaries\Win64\UDK.exe
.

**Comment by Marenz** [comment]
I assume this is fixed with the new update, if not comment again

**Comment by mrgency** [comment]
Same problem.  Just downloaded game at 4 pm on Saturday, installed it and double-clicked the desktop icon.  Get the error report message: BUILT WITH UDK has encountered a problem and needs to close.  We are sorry for the inconvenience.  

I'm not surprised my computer is having problems though.  It's pretty old and struggles through League.

**Comment by Marenz** [comment]
Please provide your logfile located at <GameFolder>/UDKGame/Launch.log

**Comment by Timoses** [comment]
Closing issue as no reply came forth.
