### ISSUE TITLE
Keyboard going crazy every now and then.

### ISSUE THREAD

**Issue by FabioTTT** [supraball/issues#57]
I'll be playing just fine when all of a sudden my character starts to stutter in place and it sounds like a bunch of keys are being pressed all at once.  Where the chat should be I see a message that reads "Speed hack detected" in black font.

Using windows 7 64 bit.  Running the 32 bit client.

**Comment by Timoses** [comment]
@Marenz ? : )

**Comment by Marenz** [comment]
The server you are playing on still has an old setting for a faulty Speedhack detection. No issue with your client, just with the server.
