### ISSUE TITLE
Goalkeeper infinite walldodges / jumps

### ISSUE THREAD

**Issue by Seikah** [supraball/issues#58]
The goalkeeper may dodge off the wall any number of times without hitting the ground. Additionally, whenever this is performed, the goalkeeper gains 2 jumps, which is sufficient to stay in the air indefinitely. This appears to be possible only with the single button dash bind, not with directional dodge input. 

(Probably not of gameplay importance, but I'm sure there's something creative out there.)

**Comment by DavidM1337** [comment]
I can only do one walljump, a second one (without touching the ground) seems impossible - or i'm not skilled enough. Anyway it's of no gameplay relevance as you said, but we should still remove it.

**Comment by Seikah** [comment]
Strange. A goalkeeper in a public game was able to replicate this. Here's a short clip to illustrate: https://www.youtube.com/watch?v=eYIqbHAUebs

**Comment by DavidM1337** [comment]
Strange, when I do it, it only works once.

**Comment by Timoses** [comment]
I can do it indefinitely...
Until in DB-hall I'm all the way at the edge of the railing..

Just just gotta keep yourself in the penalty zone, jump against the wall and dodge away from it in an angle, so that you can jump towards the wall again.

**Comment by DavidM1337** [comment]
fixed

**Comment by Marenz** [comment]
(leaving it open until new version is out to prevent others from creating the same ticket)
