### ISSUE TITLE
Opening Kickoff Bug

### ISSUE THREAD

**Issue by Fooman1** [supraball/issues#59]
On the opening kickoff clusterfuck, I was knocked into the ball at the same time as an opponent.  My UI displayed as if I had the ball(tint change and charge bar appeared), but the opponent actually had the ball.  I don't think anyone else thought I had the ball.  It eventually went away, I think, I should have paid more attention to this one, but this is all the info I have.

**Comment by Marenz** [comment]
I think we fixed this one, reopen if not.
