### ISSUE TITLE
Ball can leave the stadium on the Hall map

### ISSUE THREAD

**Issue by ghost** [supraball/issues#60]
I was playing a 3v3 pug earlier with the guys from IRC and after deflecting the ball pretty hard up in the air from the Blue-side goal it travelled up and out of the stadium on the red-side of the map. Rather than despawning for a goal kick it just travelled all the way out and the timer continued to countdown without a ball to use.

**Comment by DavidM1337** [comment]
Made the reset volumes higher, hope that fixes it
