### ISSUE TITLE
[Looking For] Server commands examples?

### ISSUE THREAD

**Issue by Hadzy-1** [supraball/issues#61]
Hello, 

I wanted to train alone so I made an empty server..
However, I can't take the full advantage except running and shooting.
Can anyone here expert with servers write a tutorial on how to use server commands, etc. ?

Cheers,
IamHadzy

**Comment by Timoses** [comment]
What do you mean by "full advantage"?

**Comment by Hadzy-1** [comment]
Timoses, Really sorry for the later reply .. I haven't played Supraball for a while now ..

What I meant by full advantage that it talks about every command.

**Comment by Timoses** [comment]
Create a server with an adminpassword (as described [here](http://supraball.net/index.php/faq)) and after logging in while being on your server with your password 
`adminlogin <yourAdminPassword>`
 for example change the map with
`adminchangemap`
or list current players with 
`adminplayerlist`
kick players with
`adminkickban`.
Restart the map with
`adminrestartmap`

**Comment by Hadzy-1** [comment]
Oh thanks Timoses, I also saw adding bots (red & blue) Can you tell me how to use that?
(again, sorry for late reply)

**Comment by Timoses** [comment]
Bots aren't added yet. The command appears in the console window but it doesn't have any functionality : P.
In a not yet foreseeable future bots will be added.
