### ISSUE TITLE
Can't launch the game

### ISSUE THREAD

**Issue by R3vorn** [supraball/issues#63]
Hi ! And sorry for my bad english.

Just, i can't launch the game i have that error. 
![sans titre](https://cloud.githubusercontent.com/assets/7853843/3237350/8f639780-f0e7-11e3-978a-678764eeb93a.png)

**Comment by Timoses** [comment]
Try executing the 32-bit version, which resides in
[...]\Supraball\Binaries\Win32\UDK.exe .

**Comment by Marenz** [comment]
Sounds like some dlls are installed wrong in your system (even before you installed supraball).
Try reinstalling the vc redistributables, both x86 and x64 bit versions.

Timos suggestion will work none the less though.

**Comment by Marenz** [comment]
Assuming fixed, reopen if not
