### ISSUE TITLE
Visuals on db-hall, possibly related to lighting

### ISSUE THREAD

**Issue by scke** [supraball/issues#65]
The middle of the floor of db-hall has rhombus shapes on it, that I _personally_ find distracting.
Is there a way to eliminate these shapes of lights from the floor the of map?

I will provide screenshots later, if requested or becomes popular.
I had tried altering various graphical settings to eliminate these things myself, but no spice.
I believe that they were not there before version 0.2.7, but that may be because some or all graphical settings were reset with the update.

Something that is not much of a concern to me, but is worth mentioning:
The walls in the map are black for me, except for when I set my "World Texture Detail" setting to the lowest of the options, or the second lowest (a bit dark though).
Is there a solution to this?
I am guessing I need to update my computer's something to be able to use other "World Texture Detail" settings.

Thanks for giving a peekerino.

**Comment by DavidM1337** [comment]
Can you show me a picture? You can just drag it into the comment box here.
Screenshot ingame works with f9.

The black walls thing, please try if that's fixed once you restarted the game.

**Comment by scke** [comment]
![screenshot00001](https://cloud.githubusercontent.com/assets/7858877/3244601/c7252cb0-f169-11e3-8bf6-3a611e612a08.png)
![screenshot00002](https://cloud.githubusercontent.com/assets/7858877/3244602/c7f6c0a4-f169-11e3-9d73-149a8b13623b.png)
I'll check to see if other World Texture Detail settings don't make black walls, at roughly 18 hours from now unfortunately, as I don't have access to a windows computer at the moment.

**Comment by DavidM1337** [comment]
Ah you're talking about the sunlight....
If you turn Dynamiclights off it will be gone.

**Comment by scke** [comment]
Thanks, turning Dynamiclights off solved the sunlight,
Restarting the game after selecting the high World Texture Detail setting solved the black walls.
Woohoo!
