### ISSUE TITLE
2.7 Can't Play

### ISSUE THREAD

**Issue by MrAah** [supraball/issues#66]
I get this error every time im done downloading, and it won't let me play.
![cupraballerror](https://cloud.githubusercontent.com/assets/7865843/3253421/f1d9f2e2-f1d7-11e3-9ad0-2b3ecc3a1a39.PNG)

**Comment by Timoses** [comment]
Looks like you have a corrupted download. Please try [redownloading the installer](http://supraball.simrai.com/supraball_0.2.7.exe).

**Comment by MrAah** [comment]
Why would you close this? I already did this, and no, it didnt work.

**Comment by Timoses** [comment]
Hm, I just downloaded from that source and it downloaded fine. But please try out this one:
http://supraball.eoreality.net/download?file=supraball_0.2.7.exe

**Comment by MrAah** [comment]
Didn't mean to snap, just frustrating. Ill retry both.

**Comment by DavidM1337** [comment]
If the file is corrupt it's really a problem of your internet connection (or the one of the server you're downloading from). The installer itself is fine, it's nothing we have anything to do with.
