### ISSUE TITLE
Changed Resolution, Can't open game even if uninstalled/re-installed

### ISSUE THREAD

**Issue by Bounce364** [supraball/issues#67]
I Changed my resolution from the default to something higher into the 1300+ & my game will no longer open in full screen.  I have tried uninstalling & re-installing but that doest seem but the game saved my previous settings!  I'm stuck!

**Comment by Timoses** [comment]
Usually it automatically recovers to your old resolution in case you don't accidently press `Down -> Enter` key combination ; ) (As this would select "Apply" in the "Do you really want to keep this resolution?" dialog). Or when you just quit before the few seconds elapse.

Please find your UDKSystemSettings.ini in your [...]\Supraball\UDKGame\Config folder.
You should be able to located the two entires:

```
ResX=xxxx
ResY=yyyy
```

Set those to anything you'd like. Alternatively you can also just delete the UDKSystemSettings.ini which will be automatically regenerated on the next game launch (though your Visual settings will be lost in that case).

**Comment by Marenz** [comment]
Assuming fixed, reopen if not.
