### ISSUE TITLE
The K.O. Slide!

### ISSUE THREAD

**Issue by detoxpenguin** [supraball/issues#7]
An issue I've ran into multiple times is when inside the opposing keeper box, and more than one person hits me at(seemingly) the same time. The player will begin to slide on the ground(away from the hit & whilst recovering health) until
A)he hits a wall, or
B)he finishes recovering health(usually approx midfield).

On both of these circumstances, the user will stand then no longer be able to move, and must relog.  Which is a hell of a hit, to be sure, but the re-log is somewhat frustrating.

**Comment by ghost** [comment]
I have experienced this as-well. Sometimes I stop sliding before I hit a wall. When that happens I have to wait for the other team to either knock me down or bounce me somewhere.

**Comment by Timoses** [comment]
This information should be really helpful when solving this bug. Thanks for reporting : )

**Comment by DavidM1337** [comment]
Can you please find exceptions to the rule?
It happening when you get only hit by one, not close to the wall?
Need to be sure it really is this.

**Comment by Timoses** [comment]
I believe it is as detoxpenguin said 

> and more than one person hits me at(seemingly) the same time.

@Swarlston ?

**Comment by detoxpenguin** [comment]
I'll see if I can gather some people together on an unpopulated server for it; we'll do further checks on this bug.

**Comment by Timoses** [comment]
https://www.youtube.com/watch?v=IrsvqDjeNpg

**Comment by Marenz** [comment]
Assuming fixed, reopen if not.
