### ISSUE TITLE
Ball duplication bug

### ISSUE THREAD

**Issue by Seikah** [supraball/issues#70]
When a player stands in the opponent's goal, on the verge of scoring, and scores by shooting at the ground with backspin, they will still be holding a ball. If this 'ghost' ball is launched before a new ball spawns, two balls will be in play. 

www.youtube.com/watch?v=o6RKYXveaDk

The ghost ball cannot be touched by players, but it can be manipulated with the real ball, and be scored with. (see www.youtube.com/watch?v=3P3iX0HHWqE )

Because this bug requires the use of the opponent's goal (a player cannot enter their own goal far enough), it is unlikely to be a problem, but this bug can be... confusing. http://i.imgur.com/RIeq0FE.jpg

I read in a different bug entry (#45) that the ball lives for a little while after scoring. Perhaps that causes this bug as well?

**Comment by Timoses** [comment]
Nice bug documentation : P. Thanks for reporting this!

**Comment by Marenz** [comment]
Lol. Nice work finding that one! Thanks for reporting! Looks like you had some fun with that :D

**Comment by Marenz** [comment]
fixed in latest version.
