### ISSUE TITLE
Weird graphical errors/glitches

### ISSUE THREAD

**Issue by ghost** [supraball/issues#71]
After changing graphics settings mid-match, i got these really weird green things that lag my computer alot. they can be walked through, and upon typing rejoin(i think thats what the command is)into the console, they go away, only to be replaced with a weird shadow in most areas, just not near me.it seems to sometimes fix itself upon rebooting the game.
![screenshot00000](https://cloud.githubusercontent.com/assets/7935338/3329823/a91d1392-f7ca-11e3-9157-ac5a555ffad4.png)

**Comment by Timoses** [comment]
Yes, we're aware of some graphical issues. Although these seem to be hardware/software dependent. We haven't quite figured this out yet.
Does restarting the whole game solve this issue? It would be great if you could post a pic of the status after restart : ).

**Comment by Marenz** [comment]
Assuming restart fixes the issue, reopen if not.

**Comment by ghost** [comment]
Oh ha sorry I completely forgot about this thing. It didn't look like restarting fixed it, I'll get back to you.
