### ISSUE TITLE
Unfixable Instant Crash?

### ISSUE THREAD

**Issue by KitinMcuff** [supraball/issues#73]
So when I opened the game up I went to options. When I went there I went to visuals and chose "My computer sucks a lot" or whatever it was called on the first option. The game instantly crashed. I tried opening the game again but now it instantly crashes. Can I have help?

**Comment by Timoses** [comment]
Thanks for reporting to our Bugtracker.

Please try deleting your `[...]\Supraball\UDKGame\Config\UDKSystemSettings.ini`.
Before you do though, it would be great if you if you could send us your log file located at `[...]\Supraball\UDKGame\Logs\Launch.log` . : ).

**Comment by Marenz** [comment]
Assuming fixed, reopen if not.
