### ISSUE TITLE
Getting inside own net on red team.

### ISSUE THREAD

**Issue by UniversaLL** [supraball/issues#75]
If you cling against the right side of the net on red team, you can get inside your own net.  This seems to only work on the red team and only on the right post.

Small video demonstrating it.
https://www.youtube.com/watch?v=caqu1fD_0mE

**Comment by DavidM1337** [comment]
the video is private

I know the bug, I just want to show it to the programmer who made the blocking volume that isn't working right

**Comment by UniversaLL** [comment]
I forgot to take it off private.  Should be good now.

**Comment by Seikah** [comment]
Same issue as #56
