### ISSUE TITLE
[BUG] Db-hall walls can change the ball trajectory

### ISSUE THREAD

**Issue by GTrebaol** [supraball/issues#76]
I've experienced that only a few times. The incriminated area seems to be just at the top of colored stripes (screenshot). It's not a lot of info but it's hard to reproduce it.

![screen](https://cloud.githubusercontent.com/assets/1216023/3404681/0cba9254-fd74-11e3-852e-a2dc25720f4a.png)

**Comment by UniversaLL** [comment]
Just want to confirm this does happen.  I made a video showcasing the spots where it does happen.  It can also occur down below in the coloured sections of the wall.

https://www.youtube.com/watch?v=D8E07M6o94k

**Comment by DavidM1337** [comment]
Thanks for reporting
We know this one, we just don't know what to do against it. Meh.

**Comment by Marenz** [comment]
related: https://github.com/supraball/issues/issues/78

**Comment by Timoses** [comment]
According to David this one is fixed.
