### ISSUE TITLE
The game doesn't respond when I open

### ISSUE THREAD

**Issue by MPertiga** [supraball/issues#77]
I installed the game and tried to open, but always the same thing happens, the game does not respond, I've tried to run this (... \ Supraball \ Binaries \ Win32 \ UDK.exe) and still the same error, and tried to also install redistributable  x86 and nothing work.
Help please!

**Comment by Timoses** [comment]
What error? Is actually an error prone popping up. Or is the screen stuck? Is the supra ball logo showing and then nothing happens (if that's the case, the shaders have to be loaded at first startup, so it might take some time when you try to run the game for the first time).

**Comment by Marenz** [comment]
Give it some time. At first run it has to compile shaders for your video card. Also, there is a Launch.log found in UDKGame/Logs, posting that will also help us to identify the problem

**Comment by mathias-baumann-sociomantic** [comment]
Is this fixed?

**Comment by MPertiga** [comment]
Yes it is, i wait for a long time and it works, thanks
