### ISSUE TITLE
Cant put to fullscreen after game is minimized

### ISSUE THREAD

**Issue by klikk** [supraball/issues#8]
The game opens in fullscreen, works fine but after alt tabbing out, or alt escaping to the taskbar I cant open it again. No matter what I do it just stucks there, cant even close it. Only task manager kill helps.
Win 7, proper PC, if you need logs or something tell me where to find it :)

**Comment by Marenz** [comment]
Yes ,logs are useful, checkout Gamefolder/UDKGame/Logs/Launch.log

**Comment by Marenz** [comment]
Assuming no longer an issue, reopen if not.
