### ISSUE TITLE
Supraball won't launch

### ISSUE THREAD

**Issue by nafiz12345** [supraball/issues#80]
Whenever i open the shortcut it, it only loads then nothing happened.
So i tried opening the launcher itself in the Program Files but it has the same issue.
I reinstalled it and it does not work :(

**Comment by Marenz** [comment]
What if you try launching [gamefolder]/Binaries/Win32/UDK.exe?

Check in the process explorer / Task manager if you find a UDK binary. If you do and it takes a lot of CPU, just give it some time, it is probably compiling the game shaders.

**Comment by Marenz** [comment]
Assuming fixed. Reopen if you still have this problem.
