### ISSUE TITLE
No servers.

### ISSUE THREAD

**Issue by dwozniakconf** [supraball/issues#81]
When i enter to Online-Mode, i haven't any servers... What wrong?

**Comment by Marenz** [comment]
Sounds like either some connection problems in which case retrying later should help. If it is consistent, make sure that no firewall is blocking the game. It tries to query supraverse.net on TCP port 8990, so make sure that isn't blocked (outgoing) by your firewall.

**Comment by dwozniakconf** [comment]
My firewall isn't blocked Supraball, because i turned off firewall of windows. Maybe another solution?

**Comment by Marenz** [comment]
What version does it show you in the menu, bottom right corner?

**Comment by dwozniakconf** [comment]
I have version 0.2.9. ~Two days ago i updated game.

**Comment by Marenz** [comment]
Can you call this URL in your browser? http://supraverse.net:8990/match

**Comment by dwozniakconf** [comment]
Only it shows:
"{"id":"1","official":false,"matchmaking":false,"ver":"","ip":"91.143.91.185","port":1234,"title":"Test server","description":"Test description","max_players":14,"max_spectators":2,"max_duration":0,"max_goals":0,"max_goal_difference":0,"current_players":1,"current_spectators":0,"current_duration":0,"current_goals_red":0,"current_goals_blue":0,"map":"cube","training":false,"tie_breaker":0,"passworded":false,"query_port":0,"players":[{"name":"Testplayer","team":0,"position":1,"ping":43,"role":"admin","rank":0}]}", nothing more..

**Comment by Marenz** [comment]
Hmm the game is pretty much doing the same thing as you just did in your browser.
One last thing we can check.. 
If you open the game and press <TAB> and then paste this:

```
    open 195.154.172.83:7000
```

Is it joining a server?

**Comment by dwozniakconf** [comment]
Yeah, i was on server...

**Comment by dwozniakconf** [comment]
No, still no servers. Litter the entire file or a particular piece?

**Comment by Marenz** [comment]
Entire file please

**Comment by dwozniakconf** [comment]
I upload this to sendspace.com because i can't upload here - https://www.sendspace.com/file/dfxdd2 . 
unless i copy the entire file

**Comment by Marenz** [comment]
Okay, I actually found some problems there. This may take some time, investigating.

**Comment by Marenz** [comment]
You're problem is a bit tougher to fix, unlikely soon.
If you are on a 64bit system, one last thing you can try is starting

```
C:\Program Files\Supraball\Binaries\Win64\udk.exe
```

and see if that fixed it.

If that doesn't help I can only offer you a workaround in the mean time:

I made a patched launcher for you which you can find at
http://timeoutd.net/launcher.exe
you will also need
http://timeoutd.net/supraball-url.reg

Run the .reg file and copy the launcher.exe to your supraball directory `C:\Program Files\Supraball\`

You should now be able to join a game directly by simply clicking on the server title on this page:

http://supraverse.net/supraball-serverlist/index.html

**Comment by Marenz** [comment]
With the next update you can use the launcher directly to join a server. Should be a decent workaround for you.
