### ISSUE TITLE
ThumbMouseButton 2.9

### ISSUE THREAD

**Issue by rndftw** [supraball/issues#82]
Hello supraball team,

since patch 2.9 i can't use ThumbMouseButton. I binded it before for "pull". But since 2.9 it doesn't let me bind it via the Options menu, neither the commandline. The buttons are working perfectly in Windows and other Applications.
I tried reinstalling the game. I have a Logitech Performance MX mouse.

I figured out, that if u disable the game support in the Logitech SetPoint Software, it is working in game as before 2.9. Maybe that helps you guys?

Greetings

**Comment by Marenz** [comment]
Hey,

thanks for the report.
Unfortuantely we probably won't fix this bug any time soon as any work on it would be obsolete once the UE4 port comes out and it is not major / game-breaking enough to justify the time we'd spend on working on it.

**Comment by Timoses** [comment]
Version 0.14.4:
Works as expected. Closing.
