### ISSUE TITLE
Can't Launch Supraball

### ISSUE THREAD

**Issue by ghost** [supraball/issues#85]
I can't open the launcher from the desktop or the actual file. The error claims that MSVCP120.dll is missing from my computer.

I tried reinstalling and I made sure I got the latest version.

**Comment by GTrebaol** [comment]
Since the dll is missing on your computer, I'd say you need to install redistribuable visual c++ for visual studio from microsoft website.

**Comment by Marenz** [comment]
GTrebaol is right, though I don't know why you're getting this error as the installe is installing exactly that.

**Comment by ghost** [comment]
The issue's been fixed and I opened the game successfully.

Thanks for the help
