### ISSUE TITLE
Can't join my own server with password.

### ISSUE THREAD

**Issue by Bubule** [supraball/issues#91]
Hello

So i created a dedicated server for my friends, we cant to play in private so i putted a password.
I coundn't join it so i looked and found this : https://github.com/supraball/issues/issues/19

I could join my server thanks to this, my friend can join too but then i putted a password, my friend could join but i coundn't find the command to connect to my own server with a password, i don't know if I need to put it in argument or it's an another command or it's not implemented yet?

**Comment by GTrebaol** [comment]
open ip:port?password=pw
