### ISSUE TITLE
Rubber-Banding While Playing

### ISSUE THREAD

**Issue by Creeperkien** [supraball/issues#93]
Over the past month, I have been having horrible rubber-banding. Sometimes when I run, I will be teleported back a few yards & while charging after I let go the bar freezes for a few seconds & then the shot goes off. It happens every game. At first I though it might be a problem with my internet, but after further investigation I found that I only had problems in Supraball. My ping is around 80 while playing, but before the rubber-banding started, my ping was around 40. I can record a few minutes of gameplay if you need to know more about my problem. Thanks.

**Comment by Marenz** [comment]
From the description it sounds like a problem with your internet or with the server. Maybe the server itself is under too much load to handle everything correctly. Try to see if it happens only on some servers.

Other than that: We only fix the most severe bugs that hit a lot of people in the current version as it will become obsolete. We rather concentrate on the new version and all the bugs that will show up there.
