### ISSUE TITLE
Can't use commands

### ISSUE THREAD

**Issue by Wumbaloo** [supraball/issues#94]
Hey! I bought a server on Simrai last week, but i can't use commands like "teleport" or "Slomo".
I go to a server yesterday and the server owner used "Slomo" so i want to do the same, thanks!

Sorry for my english, i'm french.

**Comment by GTrebaol** [comment]
Are you sure you used the right set of commands?
By the way this is not a supraball related issue.

**Comment by Wumbaloo** [comment]
I don't find any solution on google.
Yea i'm sure, i go to my server on SimRai, log as administrator and write in the console "teleport" or "slomo" and it don't works

**Comment by Dazzuh** [comment]
You have to enable cheats before you can use those commands
After you log in as admin type "admin enablecheats", then they'll work.

**Comment by Wumbaloo** [comment]
It's works, thanks!
