### ISSUE TITLE
Weird stuff with ThumbMouseButton

### ISSUE THREAD

**Issue by Fooman1** [supraball/issues#97]
I have always used my ThumbMouseButton to Pull, Dump, and Sucker.  Recently, I got a new Logitech mouse the same model as my old one and holding down the ThumbMouseButton only registers one click and does not continually pull or sucker.  I can do a temporary fix by binding the button to a keyboard key like Alt through Setpoint software.

ThumbMouseButton will not stay held on the Kick function either.  One kick and done.

This is probably just a problem with my own windows/setpoint mouse settings, but I just thought I should report it so someone else can test it out.

**Comment by DavidM1337** [comment]
some driver setting maybe?

**Comment by Fooman1** [comment]
I should have tested other games before posting, it's on my end.  It does the same in other games.  I'll get it fixed. o/

**Comment by Fooman1** [comment]
Okay, in case this comes up for others, It is a Setpoint problem.  Setpoint Game settings by default has 

"Game Detection" disabled
"Apply Game Settings when a game is detected" disabled
"Keep mouse acceleration" enabled
"Keep mouse speed" enabled
"Keep right/left hand button assignments" enabled
"Keep keypress button assignments" enabled
"Keep other button assignments" disabled

These settings work:
"Game Detection" enabled
"Apply Game Settings when a game is detected" enabled
"Keep mouse acceleration" disabled
"Keep mouse speed" disabled
"Keep right/left hand button assignments" disabled
"Keep keypress button assignments" disabled
"Keep other button assignments" disabled

**Comment by Timoses** [comment]
Glad you worked it out!
